USE myself;

ALTER TABLE user_profiles
  ADD COLUMN IF NOT EXISTS date_of_birth DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS age_verified TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sensitive_content_preference ENUM('blur','show') NOT NULL DEFAULT 'blur';

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(140) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(140) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE posts
  ADD COLUMN IF NOT EXISTS category_id BIGINT UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS slug VARCHAR(180) NULL,
  ADD COLUMN IF NOT EXISTS meta_title VARCHAR(180) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS meta_description VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_sensitive TINYINT(1) NOT NULL DEFAULT 0;

UPDATE posts SET slug = CONCAT('post-', id) WHERE slug IS NULL OR slug = '';
ALTER TABLE posts MODIFY slug VARCHAR(180) NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_posts_slug_unique ON posts(slug);

ALTER TABLE post_media ADD COLUMN IF NOT EXISTS alt_text VARCHAR(255) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS post_tags (
  post_id BIGINT UNSIGNED NOT NULL,
  tag_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (post_id, tag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS account_deletion_requests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  status ENUM('requested','processed') NOT NULL DEFAULT 'requested',
  requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO settings (setting_key, setting_value) VALUES ('site_url', 'http://localhost/app')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
