<?php
require_once __DIR__ . '/api/config/db.php';
require_once __DIR__ . '/api/helpers/seo.php';
require_once __DIR__ . '/api/helpers/story.php';
$base = site_url();
$rows = db()->query("SELECT s.title,s.slug,s.excerpt,s.featured_image,s.category,s.published_at,a.name author_name,(SELECT COALESCE(SUM(view_count),0) FROM story_views v WHERE v.story_id=s.id) views_count,(SELECT COUNT(*) FROM story_likes l WHERE l.story_id=s.id) likes_count FROM stories s JOIN admin_users a ON a.id=s.admin_id WHERE " . story_is_public_sql('s') . " ORDER BY s.published_at DESC LIMIT 100")->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>18+ Stories - myself</title><meta name="description" content="Explore curated adult stories published by the myself editorial team."><meta name="robots" content="index, follow"><link rel="canonical" href="<?=htmlspecialchars($base.'/stories')?>"><meta property="og:title" content="18+ Stories - myself"><meta property="og:description" content="Explore curated adult stories published by the myself editorial team."><meta property="og:url" content="<?=htmlspecialchars($base.'/stories')?>"><style>body{margin:0;background:#f7f8fb;color:#171717;font-family:system-ui,-apple-system,Segoe UI,sans-serif}.wrap{max-width:1100px;margin:auto;padding:24px}.hero{color:#fff;background:linear-gradient(135deg,#111827,#0f766e);border-radius:24px;padding:clamp(24px,6vw,64px)}h1{font-size:clamp(3rem,8vw,6rem);margin:0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px;margin-top:20px}.card{background:#fff;border:1px solid #e6e8ef;border-radius:18px;overflow:hidden;color:inherit;text-decoration:none}.card img{width:100%;aspect-ratio:16/10;object-fit:cover}.copy{padding:16px}.copy h2{margin:5px 0}.copy p,.meta{color:#71717a}.meta{font-size:13px;display:flex;gap:10px;flex-wrap:wrap}</style></head><body><main class="wrap"><a href="<?=$base?>/public">myself</a><section class="hero"><span>Adults only · Editorial stories</span><h1>18+ Stories</h1><p>Immersive long-form stories and audio experiences.</p></section><section class="grid"><?php foreach($rows as $s):?><a class="card" href="<?=$base?>/stories/<?=rawurlencode($s['slug'])?>"><?php if($s['featured_image']):?><img loading="lazy" src="<?=htmlspecialchars($base.'/'.$s['featured_image'])?>" alt="<?=htmlspecialchars($s['title'])?>"><?php endif;?><div class="copy"><span><?=htmlspecialchars($s['category'])?></span><h2><?=htmlspecialchars($s['title'])?></h2><p><?=htmlspecialchars($s['excerpt'])?></p><div class="meta"><span>By <?=htmlspecialchars($s['author_name'])?></span><span><?=(int)$s['views_count']?> views</span><span><?=(int)$s['likes_count']?> likes</span></div></div></a><?php endforeach;?></section></main></body></html>

