<?php
require_once __DIR__ . '/../helpers/auth.php';
$me=current_user(); $data=$_POST?:input();
$title=clean_string($data['title']??'',160);$type=clean_string($data['room_type']??'voice',20);$cat=clean_string($data['category']??'fun',20);$visibility=clean_string($data['visibility']??'public',20);
if($title===''||!in_array($type,['voice','video'],true)||!in_array($cat,['music','dating','study','gaming','fun','help'],true)||!in_array($visibility,['public','private'],true)) json_response(['success'=>false,'message'=>'Valid room details required'],422);
$password=clean_string($data['password']??'',100);$locked=($visibility==='private'||!empty($data['is_locked']))?1:0;if($locked&&!$password) json_response(['success'=>false,'message'=>'Locked room password required'],422);
$cover=null;if(!empty($_FILES['cover']['tmp_name'])){$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['cover']['tmp_name']);$allow=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($allow[$mime])||(int)$_FILES['cover']['size']>5242880)json_response(['success'=>false,'message'=>'Cover must be JPG, PNG or WEBP up to 5MB'],422);$dir=__DIR__.'/../../uploads/rooms';if(!is_dir($dir))mkdir($dir,0775,true);$cover='uploads/rooms/cover_'.$me['id'].'_'.bin2hex(random_bytes(8)).'.'.$allow[$mime];if(!move_uploaded_file($_FILES['cover']['tmp_name'],__DIR__.'/../../'.$cover))json_response(['success'=>false,'message'=>'Cover upload failed'],500);}
$stmt=db()->prepare('INSERT INTO rooms(owner_id,title,cover_image,room_type,category,visibility,language,location,is_locked,password_hash,rules,theme,active_users) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1)');
$stmt->execute([$me['id'],$title,$cover,$type,$cat,$visibility,clean_string($data['language']??'Hindi',40),clean_string($data['location']??'',120),$locked,$password?password_hash($password,PASSWORD_DEFAULT):null,clean_string($data['rules']??'',3000),clean_string($data['theme']??'midnight',40)]);
$id=(int)db()->lastInsertId();db()->prepare("INSERT INTO room_participants(room_id,user_id,role,mic_muted) VALUES(?,?,'owner',0)")->execute([$id,$me['id']]);db()->prepare('INSERT INTO room_history(room_id,user_id) VALUES(?,?)')->execute([$id,$me['id']]);json_response(['success'=>true,'room_id'=>$id]);
