import { useEffect, useState } from 'react';
import api from '../api/client';
import { requestApproximateLocation } from '../utils/location';

export default function EditProfile() {
  const [form,setForm]=useState({name:'',bio:'',city:'',state:'',gender:'',interests:'',preferred_gender_filter:'Any',account_type:'public',sensitive_content_preference:'blur',password:''});
  const [profile,setProfile]=useState(null); const [photo,setPhoto]=useState(null); const [deleteReason,setDeleteReason]=useState(''); const [msg,setMsg]=useState(''); const [locating,setLocating]=useState(false);
  const load=()=>api.get('/user/profile.php').then(({data})=>{const p=data.profile||null;setProfile(p);if(p)setForm(current=>({...current,name:p.name||'',bio:p.bio||'',city:p.city||'',state:p.state||'',gender:p.gender||'',interests:p.interests||'',preferred_gender_filter:p.preferred_gender_filter||'Any',account_type:p.account_type||'public'}));});
  useEffect(()=>{load();},[]);
  const update=(key,value)=>setForm(current=>({...current,[key]:value}));
  const submit=async e=>{e.preventDefault();setMsg((await api.post('/user/update_profile.php',form)).data.message);load();};
  const updateLocation=async()=>{setLocating(true);try{const location=await requestApproximateLocation();await api.post('/update-location.php',location);setForm(current=>({...current,state:location.state||current.state,city:location.city||current.city}));setMsg('Approximate location updated.');}catch{setMsg('Location permission denied. State and city can be updated manually.');}finally{setLocating(false);}};
  const uploadPhoto=async()=>{if(!photo)return;const fd=new FormData();fd.append('photo',photo);setMsg((await api.post('/user/upload_photo.php',fd,{headers:{'Content-Type':'multipart/form-data'}})).data.message);load();};
  const removePhoto=async()=>{setMsg((await api.post('/user/remove_photo.php')).data.message);load();};
  const deleteAccount=async()=>{if(!confirm('Delete your account? This will disable your login and create a data removal request.'))return;setMsg((await api.post('/user/delete_account.php',{reason:deleteReason})).data.message);};
  return <main className="narrow-page"><form className="panel" onSubmit={submit}><h2>Edit Profile</h2>{profile?.public_user_id&&<div className="settings-id"><span>User ID</span><strong>{profile.public_user_id}</strong></div>}<div className="photo-tools"><input className="form-control" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0])}/><button type="button" className="btn btn-outline-dark" onClick={uploadPhoto}>Upload Photo</button><button type="button" className="btn btn-outline-danger" onClick={removePhoto}>Remove Photo</button></div>
    <input className="form-control" value={form.name} placeholder="Name" onChange={e=>update('name',e.target.value)}/><textarea className="form-control" value={form.bio} placeholder="Bio" onChange={e=>update('bio',e.target.value)}/><select className="form-select" value={form.gender} onChange={e=>update('gender',e.target.value)}><option value="">Select gender</option><option>Male</option><option>Female</option><option>Other</option></select><div className="location-fields"><input className="form-control" value={form.state} placeholder="State" onChange={e=>update('state',e.target.value)}/><input className="form-control" value={form.city} placeholder="City" onChange={e=>update('city',e.target.value)}/></div><button type="button" className="btn btn-outline-dark" onClick={updateLocation} disabled={locating}><i className="bi bi-crosshair"/> {locating?'Updating...':'Update approximate location'}</button><small className="privacy-note"><i className="bi bi-shield-check"/> We use your location only to show nearby people. Exact location is never shown.</small><input className="form-control" value={form.interests} placeholder="Interests" onChange={e=>update('interests',e.target.value)}/><select className="form-select" value={form.preferred_gender_filter} onChange={e=>update('preferred_gender_filter',e.target.value)}><option>Any</option><option>Male</option><option>Female</option><option>Other</option></select><select className="form-select" value={form.account_type} onChange={e=>update('account_type',e.target.value)}><option value="public">Public</option><option value="private">Private</option></select><select className="form-select" value={form.sensitive_content_preference} onChange={e=>update('sensitive_content_preference',e.target.value)}><option value="blur">Blur sensitive content</option><option value="show">Show sensitive content</option></select><input className="form-control" type="password" placeholder="New password optional" onChange={e=>update('password',e.target.value)}/>{msg&&<div className="alert alert-info">{msg}</div>}<button className="btn btn-dark">Save discovery profile</button>
  </form><section className="panel danger-panel"><h3>Delete Account</h3><input className="form-control" placeholder="Optional reason" value={deleteReason} onChange={e=>setDeleteReason(e.target.value)}/><button className="btn btn-outline-danger" onClick={deleteAccount}>Delete my account</button></section></main>;
}
