import { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { io } from 'socket.io-client';
import api from '../api/client';
import { useAuth } from '../contexts/AuthContext';
import { WEBRTC_CONFIG, getAudioStream, stopMedia } from '../services/webrtc';
import { mediaUrl } from '../utils/media';
import UserAvatar from '../components/UserAvatar';
import RoomSeat from '../components/rooms/RoomSeat';

const SIGNALING_URL=import.meta.env.VITE_CALL_SIGNALING_URL||`${window.location.protocol}//${window.location.hostname}:3001`;
const EMOJIS=['❤️','🔥','👏','😂','🎉','👍'];

export default function Room(){
 const {roomId}=useParams();const nav=useNavigate();const {token,user}=useAuth();const [data,setData]=useState(null);const [error,setError]=useState('');const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [chat,setChat]=useState('');const [reaction,setReaction]=useState(null);const [videoForm,setVideoForm]=useState({source_type:'youtube',youtube_url:'',title:''});const [videoFile,setVideoFile]=useState(null);
 const socketRef=useRef(null),streamRef=useRef(null),peersRef=useRef(new Map()),remoteAudioRef=useRef(new Map()),videoRef=useRef(null),youtubeRef=useRef(null);
 const load=useCallback(async()=>{try{const {data:next}=await api.get(`/room/detail.php?room_id=${roomId}`);setData(next);setError('');return next;}catch(e){setError(e.response?.data?.message||'Room unavailable');}},[roomId]);
 const join=useCallback(async(pass='')=>{try{await api.post('/room/join.php',{room_id:Number(roomId),password:pass});setShowPassword(false);load();}catch(e){const msg=e.response?.data?.message||'Unable to join';if(msg==='Invalid Room Password')setShowPassword(true);setError(msg);}},[load,roomId]);
 useEffect(()=>{load().then(next=>{if(next?.my_role==='none'){if(Number(next.room.is_locked))setShowPassword(true);else join();}});const timer=setInterval(load,5000);return()=>clearInterval(timer);},[load,join]);
 const role=data?.my_role||'none',canModerate=['owner','coadmin'].includes(role),canSpeak=['owner','coadmin','speaker'].includes(role);
 const meInRoom=data?.participants?.find(p=>Number(p.user_id)===Number(user?.id)||Number(p.user_id)===Number(user?.user_id));

 const closePeers=useCallback(()=>{for(const peer of peersRef.current.values())peer.close();peersRef.current.clear();for(const audio of remoteAudioRef.current.values())audio.remove();remoteAudioRef.current.clear();stopMedia(streamRef.current);streamRef.current=null;},[]);
 const createPeer=useCallback((targetSocketId,initiator=false)=>{
   if(peersRef.current.has(targetSocketId))return peersRef.current.get(targetSocketId);const peer=new RTCPeerConnection(WEBRTC_CONFIG);peersRef.current.set(targetSocketId,peer);if(streamRef.current?.getTracks().length){streamRef.current.getTracks().forEach(t=>peer.addTrack(t,streamRef.current));}else{peer.addTransceiver('audio',{direction:'recvonly'});}peer.onicecandidate=e=>e.candidate&&socketRef.current?.emit('room:webrtc-ice',{roomId:Number(roomId),targetSocketId,candidate:e.candidate});peer.ontrack=e=>{let audio=remoteAudioRef.current.get(targetSocketId);if(!audio){audio=document.createElement('audio');audio.autoplay=true;audio.playsInline=true;audio.controls=false;audio.style.display='none';document.body.appendChild(audio);remoteAudioRef.current.set(targetSocketId,audio);}audio.srcObject=e.streams[0];audio.muted=false;audio.volume=1;audio.play().catch(()=>setError('Tap once in the room to allow audio playback'));};peer.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(peer.connectionState)){peer.close();peersRef.current.delete(targetSocketId);remoteAudioRef.current.get(targetSocketId)?.remove();remoteAudioRef.current.delete(targetSocketId);}};if(initiator)peer.createOffer().then(o=>peer.setLocalDescription(o).then(()=>o)).then(offer=>socketRef.current.emit('room:webrtc-offer',{roomId:Number(roomId),targetSocketId,offer}));return peer;
 },[roomId]);
 const youtubeCommand=useCallback((func,args=[])=>youtubeRef.current?.contentWindow?.postMessage(JSON.stringify({event:'command',func,args}),'*'),[]);
 useEffect(()=>{if(role==='none'||!token)return undefined;let cancelled=false;(async()=>{if(canSpeak){try{streamRef.current=await getAudioStream();const track=streamRef.current.getAudioTracks()[0];track.enabled=!(Number(meInRoom?.mic_muted)===1);}catch(e){setError(e.message);}}if(cancelled)return;const socket=io(SIGNALING_URL,{auth:{token},transports:['websocket','polling']});socketRef.current=socket;socket.emit('room_join',{roomId:Number(roomId)},res=>{(res?.peers||[]).forEach(p=>createPeer(p.socketId,true));});socket.on('room:user-joined',({socketId})=>createPeer(socketId,true));socket.on('room:user-left',({socketId})=>{peersRef.current.get(socketId)?.close();peersRef.current.delete(socketId);});socket.on('room:webrtc-offer',async({fromSocketId,offer})=>{const peer=createPeer(fromSocketId);await peer.setRemoteDescription(offer);const answer=await peer.createAnswer();await peer.setLocalDescription(answer);socket.emit('room:webrtc-answer',{roomId:Number(roomId),targetSocketId:fromSocketId,answer});});socket.on('room:webrtc-answer',({fromSocketId,answer})=>peersRef.current.get(fromSocketId)?.setRemoteDescription(answer));socket.on('room:webrtc-ice',({fromSocketId,candidate})=>peersRef.current.get(fromSocketId)?.addIceCandidate(candidate).catch(()=>{}));socket.on('room:message',m=>setData(d=>d?{...d,messages:[...d.messages,m].slice(-100)}:d));socket.on('room:reaction',r=>{setReaction(r);setTimeout(()=>setReaction(null),1800);});['seat_accept','seat_reject','room_lock','room_unlock','mic_mute','mic_unmute','announcement','room_close','room:user-state'].forEach(ev=>socket.on(ev,load));socket.on('video_play',p=>{youtubeCommand('seekTo',[p.position||0,true]);youtubeCommand('playVideo');if(videoRef.current){videoRef.current.currentTime=p.position||0;videoRef.current.play().catch(()=>{});}load();});socket.on('video_pause',p=>{youtubeCommand('seekTo',[p.position||0,true]);youtubeCommand('pauseVideo');if(videoRef.current){videoRef.current.currentTime=p.position||0;videoRef.current.pause();}});socket.on('video_seek',p=>{youtubeCommand('seekTo',[p.position||0,true]);if(videoRef.current)videoRef.current.currentTime=p.position||0;});})();return()=>{cancelled=true;socketRef.current?.emit('room_leave',{roomId:Number(roomId)});socketRef.current?.disconnect();socketRef.current=null;closePeers();};},[canSpeak,closePeers,createPeer,load,meInRoom?.mic_muted,role,roomId,token,youtubeCommand]);

 const action=async(action,userId=0,extra={})=>{try{await api.post('/room/action.php',{room_id:Number(roomId),action,user_id:userId,...extra});socketRef.current?.emit('room:user-state',{roomId:Number(roomId),action,userId,...extra});load();}catch(e){setError(e.response?.data?.message||'Action failed');}};
 const send=()=>{if(!chat.trim())return;socketRef.current?.emit('room:message',{roomId:Number(roomId),messageText:chat,messageType:'text'});setChat('');};
 const addVideo=async()=>{const fd=new FormData();fd.append('room_id',roomId);fd.append('action','add');Object.entries(videoForm).forEach(([k,v])=>fd.append(k,v));if(videoFile)fd.append('video',videoFile);try{await api.post('/room/video.php',fd,{headers:{'Content-Type':'multipart/form-data'}});setVideoForm({...videoForm,youtube_url:'',title:''});setVideoFile(null);load();}catch(e){setError(e.response?.data?.message||'Video add failed');}};
 const videoAction=async(action,q)=>{await api.post('/room/video.php',{room_id:Number(roomId),action,queue_id:q.id});if(action==='play')socketRef.current?.emit('video_sync',{roomId:Number(roomId),action:'play',queueId:q.id,position:0});load();};
 const current=data?.video_queue?.find(v=>v.status==='playing');
 if(!data)return <main className="room-loading">{error||'Opening room...'}</main>;
 return <main className={`live-room-page room-theme-${data.room.theme}`}>
  {showPassword&&<div className="room-modal-backdrop"><form className="room-password-card" onSubmit={e=>{e.preventDefault();join(password)}}><i className="bi bi-lock-fill"/><h2>Locked Room</h2><p>Enter room password. Owner can always enter without password.</p><input type="password" autoFocus value={password} onChange={e=>setPassword(e.target.value)} placeholder="Room password"/>{error&&<span>{error}</span>}<button className="btn btn-dark">Enter Room</button><button type="button" className="btn btn-link" onClick={()=>nav('/rooms')}>Cancel</button></form></div>}
  <header className="live-room-header"><button onClick={()=>nav('/rooms')}><i className="bi bi-arrow-left"/></button><div><span>{data.room.category} • {data.room.room_type==='video'?'Watch room':'Voice room'}</span><h1>{data.room.title}</h1></div><div className="live-room-meta"><span><i className="bi bi-people-fill"/> {data.room.active_users}</span>{Number(data.room.is_locked)===1&&<i className="bi bi-lock-fill"/>}<button onClick={()=>action('follow')}>Follow host</button></div></header>
  {data.room.announcement&&<div className="room-announcement"><i className="bi bi-megaphone-fill"/><b>Pinned</b><span>{data.room.announcement}</span></div>}
  {error&&<div className="room-error">{error}</div>}{reaction&&<div className="floating-reaction">{reaction.emoji}<small>{reaction.user?.name}</small></div>}
  <section className="live-room-main">
   <div className="room-stage">
    <section className="host-seat"><span>Host / Admin</span><div className="seat-avatar speaking"><UserAvatar user={{name:data.room.owner_name,username:data.room.owner_username,profile_photo:data.room.owner_photo}} disablePreview/><i className="bi bi-mic-fill"/></div><b>{data.room.owner_name||data.room.owner_username}</b></section>
    <section className="speaker-seats">{data.seats.map(s=><RoomSeat key={s.id} seat={s} canModerate={canModerate} onRequest={seat=>action('take_seat',0,{seat_number:seat})} onAction={action}/>)}</section>
    <div className="room-quick-actions">{canSpeak&&<button onClick={()=>action('mic',Number(meInRoom?.user_id)||0,{muted:!(Number(meInRoom?.mic_muted)===1)})}><i className={`bi ${Number(meInRoom?.mic_muted)===1?'bi-mic-fill':'bi-mic-mute-fill'}`}/> {Number(meInRoom?.mic_muted)===1?'Unmute':'Mute'}</button>}<button onClick={()=>action('raise_hand')}><i className="bi bi-hand-index-thumb"/> Raise hand</button><button onClick={()=>socketRef.current?.emit('room:reaction',{roomId:Number(roomId),emoji:'❤️'})}><i className="bi bi-heart"/> React</button><button onClick={()=>navigator.share?.({title:data.room.title,url:location.href})}><i className="bi bi-share"/> Invite</button><button onClick={()=>alert(data.room.rules||'No room rules')}><i className="bi bi-shield-check"/> Rules</button></div>
    <section className="audience-area"><h3>Audience <span>{data.participants.filter(p=>p.role==='listener').length}</span></h3><div>{data.participants.filter(p=>p.role==='listener').map(p=><button key={p.id} className={Number(p.raised_hand)?'raised':''}><UserAvatar user={p} disablePreview/><span>{p.name||p.username}</span>{Number(p.raised_hand)===1&&<i className="bi bi-hand-index-thumb-fill"/>}</button>)}</div></section>
   </div>
   <aside className="room-side-panel">
    {data.room.room_type==='video'&&<section className="watch-panel"><h3>Watch together</h3><div className="room-video-player">{current?.source_type==='youtube'?<iframe ref={youtubeRef} src={`https://www.youtube.com/embed/${current.youtube_video_id}?enablejsapi=1&autoplay=1&origin=${encodeURIComponent(window.location.origin)}`} allow="autoplay; encrypted-media" allowFullScreen title={current.title}/>:current?<video ref={videoRef} src={mediaUrl(current.uploaded_video_url)} controls={canModerate}/>:<div><i className="bi bi-play-btn"/><span>No video playing</span></div>}</div>{canModerate&&current&&<div className="video-sync-controls"><button onClick={()=>socketRef.current.emit('video_sync',{roomId:Number(roomId),action:'play',queueId:current.id,position:videoRef.current?.currentTime||0})}>Play</button><button onClick={()=>socketRef.current.emit('video_sync',{roomId:Number(roomId),action:'pause',queueId:current.id,position:videoRef.current?.currentTime||0})}>Pause</button><button onClick={()=>socketRef.current.emit('video_sync',{roomId:Number(roomId),action:'seek',queueId:current.id,position:videoRef.current?.currentTime||0})}>Sync</button></div>}<details><summary>Add / Request Video</summary><select value={videoForm.source_type} onChange={e=>setVideoForm({...videoForm,source_type:e.target.value})}><option value="youtube">YouTube URL</option><option value="upload">Browser upload</option></select><input placeholder="Video title" value={videoForm.title} onChange={e=>setVideoForm({...videoForm,title:e.target.value})}/>{videoForm.source_type==='youtube'?<input placeholder="YouTube URL" value={videoForm.youtube_url} onChange={e=>setVideoForm({...videoForm,youtube_url:e.target.value})}/>:<input type="file" accept="video/mp4,video/webm,video/quicktime" onChange={e=>setVideoFile(e.target.files?.[0])}/>}<button onClick={addVideo}>{canModerate?'Add to queue':'Send request'}</button></details><div className="video-queue">{data.video_queue.map(q=><div key={q.id}><i className={`bi ${q.source_type==='youtube'?'bi-youtube':'bi-file-play'}`}/><span><b>{q.title}</b><small>{q.status} • {q.requested_by_name}</small></span>{canModerate&&<span><button onClick={()=>videoAction('play',q)}>Play</button><button onClick={()=>videoAction('remove',q)}>×</button></span>}</div>)}</div></section>}
    <section className="room-user-list-panel"><h3>Live users <span>{data.participants.length}</span></h3><div className="room-user-list">{data.participants.map(p=><div key={p.user_id} className={`room-user-row role-${p.role}`}><UserAvatar user={p} disablePreview/><span><b>{p.name||p.username}</b><small>{p.role}{Number(p.mic_muted)===1?' • muted':' • mic on'}{Number(p.raised_hand)===1?' • hand raised':''}</small></span>{canModerate&&p.role!=='owner'&&<div><button onClick={()=>action('mic',p.user_id,{muted:!Number(p.mic_muted)})}><i className={`bi ${Number(p.mic_muted)?'bi-mic-fill':'bi-mic-mute-fill'}`}/></button><button onClick={()=>action('kick',p.user_id)}><i className="bi bi-person-x"/></button></div>}</div>)}</div></section>
    {canModerate&&<section className="room-admin-panel"><h3>Room controls</h3><div><button onClick={()=>action('lock',0,{locked:!Number(data.room.is_locked),password:prompt('Password for lock (leave empty to keep current)')||''})}><i className="bi bi-lock"/> Lock</button><button onClick={()=>action('announcement',0,{announcement:prompt('Pinned announcement')||''})}><i className="bi bi-megaphone"/> Pin</button>{role==='owner'&&<button onClick={()=>action('close')}><i className="bi bi-x-octagon"/> Close</button>}</div></section>}
    <section className="room-chat"><h3>Room chat</h3><div className="room-chat-scroll">{data.messages.map(m=><div key={m.id} className={`room-chat-message ${m.message_type}`} >{m.message_type!=='system'&&<UserAvatar user={m} disablePreview/>}<span>{m.message_type!=='system'&&<b>{m.name||m.username}</b>}{m.message_text}</span></div>)}</div><div className="room-emoji-row">{EMOJIS.map(e=><button key={e} onClick={()=>socketRef.current?.emit('room:reaction',{roomId:Number(roomId),emoji:e})}>{e}</button>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={chat} onChange={e=>setChat(e.target.value)} placeholder="Message everyone"/><button><i className="bi bi-send-fill"/></button></form></section>
   </aside>
  </section>
  <button className="leave-room-button" onClick={async()=>{await action('leave');nav('/rooms')}}><i className="bi bi-box-arrow-right"/> Leave Room</button>
 </main>;
}
